; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = genericCH32V203C8T6
; default_envs = native

; Basic project configuration
[env:genericCH32V203C8T6]
; platform = ch32v
platform = https://github.com/Community-PIO-CH32V/platform-ch32v.git
board = genericCH32V203C8T6
framework = freertos
upload_protocol = isp
extra_scripts = post:generate_uf2.py
lib_deps = adafruit/Adafruit TinyUSB Library@^3.7.7

; Native configuration for testing on the host machine
[env:native]
platform = native
build_src_filter = -<*>
; build_src_filter = +<*> -<main.c>
lib_deps = adafruit/Adafruit TinyUSB Library@^3.7.7
