name: PlatformIO CI

on:
  push:
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'test/**'
      - 'platformio.ini'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Cache PlatformIO Core
        uses: actions/cache@v5
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
            ~/.platformio/packages
          # platformio.iniの内容が変わったらキャッシュを再作成する
          key: ${{ runner.os }}-pio-${{ hashFiles('platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-pio-

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run

      - name: Check Build Artifacts
        run: ls -laR

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ch32v203-firmware
          path: |
            .pio/build/**/firmware.bin
            .pio/build/**/firmware.hex
            .pio/build/**/firmware.elf
            .pio/build/**/firmware.uf2